### ISSUE TITLE
Erro inicial na api

### ISSUE THREAD

**Issue by warquia** [elemke/sicoob-pix#1]
Boa tarde, Estou tendo um erro `Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 58: could not load PEM client certificate, OpenSSL error error:02001002:system library:fopen:No such file or directory, (no key found, wrong pass phrase, or wrong file format?) (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api-homol.sicoob.com.br/cooperado/pix/token in C:\xampp\htdocs\suporte\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 211`

Porém porem creio que possivelmente esteja preenchendo o .env errado:
SICOOBPIX_CLIENT_ID='27Cg4fEDJvbtrS0mcfXHD7X'
SICOOBPIX_CLIENT_SECRET='_s9Wv9c5pTLruRQNYh'
SICOOBPIX_AMBIENTE_HOMOLOGACAO=true
SICOOBPIX_CAMINHO_CERT_PUBLICO='./LOJA 1.cer'
SICOOBPIX_SENHA_CERT_PUBLICO='123456'
SICOOBPIX_CAMINHO_CERT_PRIVADO='./LOJA 1.pfx'
SICOOBPIX_SENHA_CERT_PRIVADO='123456'

o Cert. Publico foi gerado via windows de um certificado A1.

Ta correta essa configuração? devo exportar via windows para obter os dados solicitado nesse projeto?

**Comment by SiqueiraAndre** [comment]
Boa tarde,  Estou tendo e tbm estou praticamente com a mesma dúvida colega relatou acima:

Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 58: could not load PEM client certificate, OpenSSL error error:0906D06C:PEM routines:PEM_read_bio:no start line, (no key found, wrong pass phrase, or wrong file format?) (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api-homol.sicoob.com.br/cooperado/pix/token in /var/www/unydade/task/www/sicoob-pix/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211 Stack trace: #0 /var/www/unydade/task/www/sicoob-pix/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 /var/www/unydade/task/www/sicoob-pix/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 /var/www/unydade/task/www/sicoob-pix/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\ in /var/www/unydade/task/www/sicoob-pix/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 211

.env
SICOOBPIX_CLIENT_ID='kBnft9EW9W9MbHjgMnvOZksmzxEa'
SICOOBPIX_CLIENT_SECRET='jMg0QDVt1dmBpf4U3efFDj0X3jEa'
SICOOBPIX_AMBIENTE_HOMOLOGACAO=true
SICOOBPIX_CAMINHO_CERT_PUBLICO='./cert/public.pem'
SICOOBPIX_SENHA_CERT_PUBLICO=''
SICOOBPIX_CAMINHO_CERT_PRIVADO='./cert/key.p12'
SICOOBPIX_SENHA_CERT_PRIVADO=1234

Outra dúvida tenho que usar certificado A1  ou posso gerar um certificado auto assinado para este procedimento?

**Comment by SiqueiraAndre** [comment]
Boa tarde, Estou tendo e tbm estou praticamente com a mesma dúvida colega relatou acima:

Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 58: could not load PEM client certificate, OpenSSL error error:0906D06C:PEM routines:PEM_read_bio:no start line, (no key found, wrong pass phrase, or wrong file format?) (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api-homol.sicoob.com.br/cooperado/pix/token in /var/www/unydade/task/www/sicoob-pix/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211 Stack trace: #0 /var/www/unydade/task/www/sicoob-pix/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 /var/www/unydade/task/www/sicoob-pix/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 /var/www/unydade/task/www/sicoob-pix/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\ in /var/www/unydade/task/www/sicoob-pix/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 211

.env
SICOOBPIX_CLIENT_ID='0000000000000'
SICOOBPIX_CLIENT_SECRET='xxxxxxxxxxxxx'
SICOOBPIX_AMBIENTE_HOMOLOGACAO=true
SICOOBPIX_CAMINHO_CERT_PUBLICO='./cert/public.pem'
SICOOBPIX_SENHA_CERT_PUBLICO=''
SICOOBPIX_CAMINHO_CERT_PRIVADO='./cert/key.p12'
SICOOBPIX_SENHA_CERT_PRIVADO=1234

Outra dúvida tenho que usar certificado A1 ou posso gerar um certificado auto assinado para este procedimento?

**Comment by warquia** [comment]
Conseguir resolver. Passei o caminho absoluto nas configurações:

SICOOBPIX_CAMINHO_CERT_PUBLICO= 'C:\xampp\htdocs\suporte\testes/loja1.cer'
SICOOBPIX_CAMINHO_CERT_PRIVADO='C:\xampp\htdocs\suporte\testes/loja1.pem'

**Comment by SiqueiraAndre** [comment]
> guir resolver. Passei o caminho absoluto nas configuraçõ

Você usou qual tipo de certificado? teve que comprar ou conseguiu gerar autoassinado?

**Comment by warquia** [comment]
Bom dia, eu usei uma certificado modelo A1(comprado) disponivel aqui na empresa, após isso exportei o certificado no modelo .CER no windows e gerei a private key no openssl mostrado [aqui](https://tdn.totvs.com/pages/releaseview.action?pageId=496016323)
agora não sei te informar se funciona no certificado autoassinado

**Comment by elemke** [comment]
Bom dia!
Não pode ser certificado autoassinado @SiqueiraAndre, precisa ser de alguma entidade certificadora ICP Brasil. Além do link disponbilizado pela @warquia, você seguir instruções do próprio Sicoob: [https://developers.sicoob.com.br/#!/documentacao](https://developers.sicoob.com.br/#!/documentacao) - Menu Segurança.
