### ISSUE TITLE
CobOperacaoInvalida

### ISSUE THREAD

**Issue by cesarlopes** [elemke/sicoob-pix#2]
Olá,

Esse projeto ainda funciona?

Fiz um teste e consegui gerar o token de acesso, mas ao tentar criar um pix ou consultar esta retornando ERRO 400 : CobOperacaoInvalida

**Comment by elemke** [comment]
Boa tarde, @cesarlopes 
Acabei de subir a versão 2.0 com alguns ajustes. De qualquer forma, o erro informado normalmente é porque está sendo enviada uma chave pix inexistente.
